-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnZK/rGtg42Jp2vKt
C6wNSZ+MAiU9uMXtjlQSBLWJixagCgYIKoZIzj0DAQehRANCAASfjOEUxi84zcal
ycCtp/hfTytWf3iTxgQJs1J+BWSukpXeFqNTO9gbmMEvlGTkFGR20fOK8D+CMvxS
plS+h3Mh
-----END PRIVATE KEY-----